Update patch set 9
Patch Set 9: Code-Review-1

I fixed the creation, but the deletion of subnetRoute is still failing with this exception, 

java.lang.NullPointerException: RouteDistinguisher cannot be null or empty!
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:226)[38:com.google.guava:18.0.0]
	at org.opendaylight.netvirt.vpnmanager.VpnSubnetRouteHandler.deleteSubnetRouteFromFib(VpnSubnetRouteHandler.java:748)[339:org.opendaylight.netvirt.vpnmanager-impl:0.4.0.SNAPSHOT]
	at org.opendaylight.netvirt.vpnmanager.VpnSubnetRouteHandler.onSubnetDeletedFromVpn(VpnSubnetRouteHandler.java:279)[339:org.opendaylight.netvirt.vpnmanager-impl:0.4.0.SNAPSHOT]
	at org.opendaylight.netvirt.vpnmanager.SubnetmapChangeListener.update(SubnetmapChangeListener.java:114)[339:org.opendaylight.netvirt.vpnmanager-impl:0.4.0.SNAPSHOT]
	at org.opendaylight.netvirt.vpnmanager.SubnetmapChangeListener.update(SubnetmapChangeListener.java:28)[339:org.opendaylight.netvirt.vpnmanager-impl:0.4.0.SNAPSHOT]
	at org.opendaylight.genius.datastoreutils.AsyncDataTreeChangeListenerBase$DataTreeChangeHandler.run(AsyncDataTreeChangeListenerBase.java:157)[298:org.opendaylight.genius.mdsalutil-api:0.2.0.SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_121]

Need to further figure out !

Patch-set: 9
Label: Code-Review=-1