Update patch set 12
Patch Set 12:

(1 comment)

Hi all,

It seems the error is caused by the fact that thrift binary dependency has already been loaded,and thus it is not possible to load a new one.
I think the problem is related to the thrift dependency introduced.
I see two solutions:
- one could try to remove the thrift dependency from bgpmanager-impl, so that thrift is referenced only once ( and not two).
- one could try to remove all the calls to thrift call AFI.get_value, and replace it by a real bgpmanager-api implementation of AFI enumerate.





installFeatureCatchAndLog(org.opendaylight.odlparent.featuretest.SingleFeatureTest)[repoUrl: file:/w/workspace/netvirt-verify-nitrogen-mvn33-openjdk8/vpnservice/features/odl-netvirt-federation/target/feature/feature.xml, Feature: odl-netvirt-federation 0.5.0.SNAPSHOT]  Time elapsed: 19.488 sec  <<< ERROR!
org.osgi.framework.BundleException: A bundle is already installed with the name "org.apache.thrift" and version "0.9.1"

Patch-set: 12