Update patch set 7
Patch Set 7: Code-Review-2

patch added new exceptions:

2017-09-19 06:13:56,379 | INFO  | nsole user karaf | core                             | 112 - org.apache.karaf.log.core - 4.0.9 | ROBOT MESSAGE: Starting test Check Vm Instances Have Ip Address
java.lang.IllegalArgumentException: All keys must be specified for class org.opendaylight.yang.gen.v1.urn.opendaylight.genius.interfacemanager.meta.rev160406.dpn.to._interface.list.DpnToInterfaceKey. Missing key is getDpid. Supplied key is DpnToInterfaceKey []

2017-09-19 06:40:00,346 | INFO  | nsole user karaf | core                             | 112 - org.apache.karaf.log.core - 4.0.9 | ROBOT MESSAGE: Starting test Delete Vm Instances
2017-09-19 06:40:02,091 | ERROR | nPool-2-worker-2 | DataStoreJobCoordinator          | 243 - org.opendaylight.genius.mdsalutil-api - 0.4.0.SNAPSHOT | Exception when executing jobEntry: JobEntry{key='VPNINTERFACE-null', mainWorker=org.opendaylight.netvirt.fibmanager.VrfEntryListener$CleanupVpnInterfaceWorker@2d8aeb02, rollbackWorker=null, retryCount=0, futures=null}
java.lang.IllegalArgumentException: All keys must be specified for class org.opendaylight.yang.gen.v1.urn.huawei.params.xml.ns.yang.l3vpn.rev140815.vpn.interfaces.VpnInterfaceKey. Missing key is getName. Supplied key is VpnInterfaceKey []

Patch-set: 7
Reviewer: Gerrit User 773 <773@7fc14799-209e-464c-9743-7a06c2c21a81>
Label: Code-Review=-2