Update patch set 2
Patch Set 2: Code-Review-1

looks like some new exceptions

2017-11-16 22:05:25,732 | ERROR | nPool-1-worker-3 | VpnFootprintService              | 346 - org.opendaylight.netvirt.vpnmanager-impl - 0.6.0.SNAPSHOT | removeOrUpdateVpnToDpnList: Error removing from dpnToVpnList for vpn 6b3224f1-5e55-4ceb-ae9a-0b2912b025bf vpnId 100025 interface 760f2d17-aca7-4305-983d-ce9beac4e3be dpn 272684322231222
java.util.concurrent.ExecutionException: OptimisticLockFailedException{message=Optimistic lock failed., errorList=[RpcError [message=Optimistic lock failed., severity=ERROR

Patch-set: 2