Update patch set 1
Patch Set 1:

@Tom, so is the suggestion to use the following [1] capability or to remove the capability itself. Please suggest.

[1] <capability>urn:opendaylight:params:xml:ns:yang:controller:config:entity-ownership-service?module=opendaylight-entity-ownership-service&amp;revision=2016-02-26</capability>


In case, its the former i did try with it and seeing the following error.

2016-07-21 19:29:20,824 | ERROR | config-pusher    | ConfigPusherImpl                 | 140 - org.opendaylight.controller.config-persister-impl - 0.5.0.SNAPSHOT | Unable to push configuration due to missing yang models. Yang models that are missing, but required by the configuration: [urn:opendaylight:params:xml:ns:yang:controller:config:entity-ownership-service?module=entity-ownership-service&revision=2016-02-26]. For each mentioned model check:  1. that the mentioned yang model namespace/name/revision is identical to those in the yang model itself 2. the yang file is present in the system 3. the bundle with that yang file is present in the system and active 4. the yang parser did not fail while attempting to parse that model
2016-07-21 19:29:20,825 | ERROR | config-pusher    | ConfigPusherImpl                 | 140 - org.opendaylight.controller.config-persister-impl - 0.5.0.SNAPSHOT | Failed to apply configuration snapshot: bgpmanager-impl-default-config.xml(odl-netvirt-vpnservice-openstack,odl-netvirt-vpnservice-openstack)
java.lang.IllegalStateException: Unable to push configuration due to missing yang models. Required yang models that are missing: [urn:opendaylight:params:xml:ns:yang:controller:config:entity-ownership-service?module=entity-ownership-service&revision=2016-02-26]
        at org.opendaylight.controller.config.persist.impl.ConfigPusherImpl.waitForCapabilities(ConfigPusherImpl.java:209)[140:org.opendaylight.controller.config-persister-impl:0.5.0.SNAPSHOT]
        at org.opendaylight.controller.config.persist.impl.ConfigPusherImpl.pushConfigWithConflictingVersionRetries(ConfigPusherImpl.java:159)[140:org.opendaylight.controller.config-persister-impl:0.5.0.SNAPSHOT]
        at org.opendaylight.controller.config.persist.impl.ConfigPusherImpl.internalPushConfigs(ConfigPusherImpl.java:129)[140:org.opendaylight.controller.config-persister-impl:0.5.0.SNAPSHOT]
        at org.opendaylight.controller.config.persist.impl.ConfigPusherImpl.processSingle(ConfigPusherImpl.java:83)[140:org.opendaylight.controller.config-persister-impl:0.5.0.SNAPSHOT]
        at org.opendaylight.controller.config.persist.impl.ConfigPusherImpl.process(ConfigPusherImpl.java:74)[140:org.opendaylight.controller.config-persister-impl:0.5.0.SNAPSHOT]
        at org.opendaylight.controller.config.persist.impl.osgi.ConfigPersisterActivator$2.run(ConfigPersisterActivator.java:131)[140:org.opendaylight.controller.config-persister-impl:0.5.0.SNAPSHOT]
        at java.lang.Thread.run(Thread.java:745)[:1.8.0_92]
Caused by: org.opendaylight.controller.config.persist.impl.ConfigPusherImpl$NotEnoughCapabilitiesException: Not enough capabilities for bgpmanager-impl-default-config.xml(odl-netvirt-vpnservice-openstack,odl-netvirt-vpnservice-openstack). Expected but not found: [urn:opendaylight:params:xml:ns:yang:controller:config:entity-ownership-service?module=entity-ownership-service&revision=2016-02-26]

Patch-set: 1
Reviewer: Gerrit User 5197 <5197@7fc14799-209e-464c-9743-7a06c2c21a81>
Label: Verified=0