Update patch set 5
Patch Set 5:

This patch was reverted. it created an extra exception in the CSIt runs

https://logs.opendaylight.org/releng/jenkins092/netvirt-csit-1node-openstack-ocata-gate-stateful-nitrogen/86/odl1_exception.log.gz

SubnetRouteInterfaceListener add: Exception observed in handling addition for VPN Interface 163438310658299:br-physnet1-pa:trunk.
java.lang.IllegalArgumentException: Supplied value "163438310658299:br-physnet1-pa:trunk" does not match required pattern "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"

Patch-set: 5