Update patch set 2
Patch Set 2: Code-Review-1

there was an additional exception created on the test run. Rerunning csit. test-netvirt-current

2017-09-21 05:57:00,668 | INFO  | h for user karaf | command                          | 364 - org.apache.karaf.log.command - 3.0.8 | ROBOT MESSAGE: Starting test tempest.scenario.test_security_groups_basic_ops.TestSecurityGroupsBasicOps
2017-09-21 06:03:17,932 | ERROR | eChangeHandler-0 | ExternalRoutersListener          | 342 - org.opendaylight.netvirt.natservice-impl - 0.4.2.SNAPSHOT | handleDisableSnat : Exception while handling disableSNAT for router :84bf22b8-6f72-47fd-9d57-4296065a96b1
java.lang.IllegalArgumentException: All keys must be specified for class org.opendaylight.yang.gen.v1.urn.opendaylight.netvirt.l3vpn.rev130911.vpn.instance.op.data.VpnInstanceOpDataEntryKey. Missing key is getVrfId. Supplied key is VpnInstanceOpDataEntryKey []
	at org.opendaylight.genius.datastoreutils.SingleTransactionDataBroker.syncReadOptionalAndTreatReadFailedExceptionAsAbsentOptional(SingleTransactionDataBroker.java:158)[292:org.opendaylight.genius.mdsalutil-api:0.2.2.SNAPSHOT]
2

Patch-set: 2