Update patch set 4
Patch Set 4: Code-Review-1

last two run on stable/nitrogen have both had the below exception. Can you look if this is related?

looks like new exceptions in the log:
2017-08-29 15:21:40,867 | INFO  | nsole user karaf | core                             | 112 - org.apache.karaf.log.core - 4.0.9 | ROBOT MESSAGE: Starting test Delete Networks
org.opendaylight.yangtools.yang.data.api.schema.tree.ModifiedNodeDoesNotExistException: Node /(urn:opendaylight:inventory?revision=2013-08-19)nodes/node/node[{(urn:opendaylight:inventory?revision=2013-08-19)id=openflow:0}] does not exist. Cannot apply modification to its children.
org.opendaylight.yangtools.yang.data.api.schema.tree.ModifiedNodeDoesNotExistException: Node /(urn:opendaylight:inventory?revision=2013-08-19)nodes/node/node[{(urn:opendaylight:inventory?revision=2013-08-19)id=openflow:0}] does not exist. Cannot apply modification to its children.
TransactionCommitFailedException{message=Data did not pass validation., errorList=[RpcError [message=Data did not pass validation., severity=ERROR, errorType=APPLICATION, tag=operation-failed, applicationTag=null, info=null, cause=org.opendaylight.yangtools.yang.data.api.schema.tree.ModifiedNodeDoesNotExistException: Node /(urn:opendaylight:inventory?revision=2013-08-19)nodes/node/node[{(urn:opendaylight:inventory?revision=2013-08-19)id=openflow:0}] does not exist. Cannot apply modification to its children.]]}
Caused by: org.opendaylight.yangtools.yang.data.api.schema.tree.ModifiedNodeDoesNotExistException: Node /(urn:opendaylight:inventory?revision=2013-08-1

Patch-set: 4
Label: Code-Review=-1