Update patch set 6
Patch Set 6:

(1 comment)

this might be one new exception in the csit, but I am not sure how this patch would have caused it.

017-11-15 04:05:09,097 | ERROR | nPool-1-worker-2 | JobCoordinatorImpl               | 261 - org.opendaylight.infrautils.jobcoordinator-impl - 1.3.0.SNAPSHOT | Runnnable likely about to terminate thread due to uncaught exception; but here is useful debugging context: JobEntry{key='elaninterface-3dc8583a-0ab4-41ae-b816-4db5cd764b95', mainWorker=org.opendaylight.netvirt.elan.internal.ElanInstanceManager$$Lambda$759/740397703@333d1009, rollbackWorker=null, retryCount=6, futures=[null, com.google.common.util.concurrent.ImmediateFuture$ImmediateSuccessfulCheckedFuture@4c484d29, com.google.common.util.concurrent.ImmediateFuture$ImmediateSuccessfulCheckedFuture@713223c9]}
java.lang.NullPointerException: at index 0

Patch-set: 6