Update patch set 3
Patch Set 3: Code-Review-1

Manu, can you look at the exceptions in the last run? Looks like some known ones are there but there is a new one: java.lang.NullPointerException: at index 0. There is also an ElanUtils exception right after a bindling log as shown below.

https://logs.opendaylight.org/releng/jenkins092/netvirt-csit-1node-openstack-ocata-gate-stateful-oxygen/198/odl1_karaf.log.gz

The run had: 2017-10-27 19:22:48,077 | INFO  | nPool-1-worker-1 | ngressServicesConfigUnbindHelper | 242 - org.opendaylight.genius.interfacemanager-impl - 0.4.0.SNAPSHOT | unbinding ingress service elan.b6997e56-b982-4999-a323-06e8f2bce864.255504673530941:br-physnet1-pa:trunk for vlan port: 255504673530941:br-physnet1-pa:trunk
2017-10-27 19:22:48,078 | ERROR | nPool-1-worker-3 | ElanUtils                        | 324 - org.opendaylight.netvirt.elanmanager-impl - 0.6.0.SNAPSHOT | Error writing to datastore {}
java.util.concurrent.ExecutionException: OptimisticLockFailedException{message=Optimistic lock failed., errorList=[RpcError [message=Optimistic lock failed., severity=ERROR, errorType=APPLICATION, tag=resource-denied, applicationTag=null, info=null, cause=org.opendaylight.yangtools.yang.data.api.schema.tree.ConflictingModificationAppliedException: Node was deleted by other transaction.]]}
	at org.opendaylight.mdsal.common.api.MappingCheckedFuture.wrapInExecutionException(MappingCheckedFuture.java:66)[271:org.opendaylight.mdsal.common-api:2.4.0.SNAPSHOT]

The group-id and adjacency exceptions can be ignored as they are known.

Patch-set: 3