Update patch set 3
Patch Set 3:

The exception is from Tempest API test. Logs at [1] say MAC address is missing

2017-06-11 14:10:34,672 | WARN  | eChangeHandler-0 | VpnManagerImpl                   | 332 - org.opendaylight.netvirt.vpnmanager-impl - 0.4.1.Carbon | Failed to handle router GW flow in GW-MAC table. MAC address is missing for router-id 4bd8ea89-5d27-4bc6-a609-75023331bec8
2017-06-11 14:10:34,672 | INFO  | eChangeHandler-0 | VpnManagerImpl                   | 332 - org.opendaylight.netvirt.vpnmanager-impl - 0.4.1.Carbon | Installing ARP responder flows for 4bd8ea89-5d27-4bc6-a609-75023331bec8 fixed-ips [10.10.10.4] on switch 250919249445938
2017-06-11 14:10:34,675 | ERROR | eChangeHandler-0 | AsyncDataTreeChangeListenerBase  | 291 - org.opendaylight.genius.mdsalutil-api - 0.2.1.Carbon | Thread terminated due to uncaught exception: AsyncDataTreeChangeListenerBase-DataTreeChangeHandler-0
java.lang.NullPointerException: Supplied value may not be null
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:226)[38:com.google.guava:18.0.0]
	at org.opendaylight.yang.gen.v1.urn.ietf.params.xml.ns.yang.ietf.yang.types.rev130715.MacAddress.<init>(MacAddress.java:50)[54:org.opendaylight.mdsal.model.ietf-yang-types-20130715:2013.7.15.10_1-Carbon]
	at org.opendaylight.netvirt.vpnmanager.arp.responder.ArpResponderUtil.getActions(ArpResponderUtil.java:205)[332:org.opendaylight.netvirt.vpnmanager-impl:0.4.1.Carbon]

I have parsed the log file [1] to get router id and searched for "mac" in the parsed data [2]. MAC is allocated to VpnInterface (L26) but MAC is missing for the corresponding router-id

[1]. https://logs.opendaylight.org/releng/jenkins092/netvirt-csit-1node-openstack-newton-nodl-v2-upstream-stateful-carbon/670/odl1_karaf.log.gz
[2]. http://paste.openstack.org/show/612362/

Patch-set: 3