Update patch set 2
Patch Set 2:

Build are getting failed due to yang-tool issue.

nstallFeature(org.opendaylight.odlparent.featuretest.SingleFeatureTest)[repoUrl: file:/w/workspace/netvirt-distribution-check-carbon/distribution/features-test/target/classes/features.xml, Feature: odl-integration-compatible-with-all 0.6.0-SNAPSHOT]  Time elapsed: 304.764 sec  <<< ERROR!
java.lang.IllegalStateException: Can't install feature odl-integration-compatible-with-all/0.6.0-SNAPSHOT: 	
Could not start bundle mvn:org.opendaylight.netconf/sal-netconf-connector/1.5.0-SNAPSHOT in feature(s) odl-netconf-connector-1.2.0-SNAPSHOT: The bundle "org.opendaylight.netconf.sal-netconf-connector_1.5.0.SNAPSHOT [402]" could not be resolved. Reason: Missing Constraint: Import-Package: org.opendaylight.yangtools.sal.binding.generator.impl; version="[0.10.0,1.0.0)"
	at org.apache.karaf.features.internal.FeaturesServiceImpl.installFeature(FeaturesServiceImpl.java:403)

Patch-set: 2