Update patch set 9
Patch Set 9: Code-Review-1

Looks like patch added some extra exceptions.

ROBOT MESSAGE: Starting test Create External Network And Subnet
org.opendaylight.yangtools.yang.data.api.schema.tree.ModifiedNodeDoesNotExistException: Node /(urn:opendaylight:genius:interfacemanager:servicebinding?revision=2016-04-06)service-bindings/services-info/services-info[{(urn:opendaylight:genius:interfacemanager:servicebinding?revision=2016-04-06)interface-name=211800033138399:br-physnet1-pa:trunk, (urn:opendaylight:genius:interfacemanager:servicebinding?revision=2016-04-06)service-mode=(urn:opendaylight:genius:interfacemanager:servicebinding?revision=2016-04-06)service-mode-ingress}] does not exist. Cannot apply modification to its children.

Patch-set: 9