Update patch set 2
Patch Set 2:

Hi Faseela,

Whenever we try to unbind an external Interface from a VPN as part of delete networks executed by CSIT, we are getting the below exception:

Can you please offer any pointers/insights?

2017-09-27 10:43:31,349 | INFO  | nPool-2-worker-1 | ngressServicesConfigUnbindHelper | 237 - org.opendaylight.genius.interfacemanager-impl - 0.4.0.SNAPSHOT | unbinding ingress service vpn.d2565876-e19d-48b0-839b-5a98ff10e79b.150595073270361:br-physnet1-pa:trunk for vlan port: 150595073270361:br-physnet1-pa:trunk
2017-09-27 10:43:31,352 | WARN  | rd-dispatcher-34 | ShardDataTree                    | 213 - org.opendaylight.controller.sal-distributed-datastore - 1.7.0.SNAPSHOT | member-1-shard-inventory-config: Store Tx member-1-datastore-config-fe-0-txn-22443-0: Data validation failed for path /(urn:opendaylight:inventory?revision=2013-08-19)nodes/node/node[{(urn:opendaylight:inventory?revision=2013-08-19)id=openflow:0}].
org.opendaylight.yangtools.yang.data.api.schema.tree.ModifiedNodeDoesNotExistException: Node /(urn:opendaylight:inventory?revision=2013-08-19)nodes/node/node[{(urn:opendaylight:inventory?revision=2013-08-19)id=openflow:0}] does not exist. Cannot apply modification to its children.
	at 

Vivek

Patch-set: 2
Label: Verified=0