Fix missing init for VpnPseudoPortListener
2016-10-21 17:21:27,920 | ERROR | rint Extender: 1 | BlueprintContainerImpl           | 15 - org.apache.aries.blueprint.core - 1.6.1 | Unable to start blueprint container for bundle org.opendaylight.netvirt.cloud-servicechain-impl/0.4.0.SNAPSHOT
org.osgi.service.blueprint.container.ComponentDefinitionException: Component 'vpnPseudoPortListener' does not have init-method: init
    at org.apache.aries.blueprint.container.BeanRecipe.getInitMethod(BeanRecipe.java:645)[15:org.apache.aries.blueprint.core:1.6.1]
        at org.apache.aries.blueprint.container.BeanRecipe.internalCreate2(BeanRecipe.java:833)[15:org.apache.aries.blueprint.core:1.6.1]
            at org.apache.aries.blueprint.container.BeanRecipe.internalCreate(BeanRecipe.java:811)[15:org.apache.aries.blueprint.core:1.6.1]
                at org.apache.aries.blueprint.di.AbstractRecipe$1.call(AbstractRecipe.java:79)[15:org.apache.aries.blueprint.core:1.6.1]
                    at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_102]
                        at org.apache.aries.blueprint.di.AbstractRecipe.create(AbstractRecipe.java:88)[15:org.apache.aries.blueprint.core:1.6.1]
                            at org.apache.aries.blueprint.container.BlueprintRepository.createInstances(BlueprintRepository.java:255)[15:org.apache.aries.blueprint.core:1.6.1]
                                at org.apache.aries.blueprint.container.BlueprintRepository.createAll(BlueprintRepository.java:186)[15:org.apache.aries.blueprint.core:1.6.1]
                                    at org.apache.aries.blueprint.container.BlueprintContainerImpl.instantiateEagerComponents(BlueprintContainerImpl.java:724)[15:org.apache.aries.blueprint.core:1.6.1]
                                        at org.apache.aries.blueprint.container.BlueprintContainerImpl.doRun(BlueprintContainerImpl.java:411)[15:org.apache.aries.blueprint.core:1.6.1]
                                            at org.apache.aries.blueprint.container.BlueprintContainerImpl.run(BlueprintContainerImpl.java:276)[15:org.apache.aries.blueprint.core:1.6.1]
                                                at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_102]
                                                    at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_102]
                                                        at org.apache.aries.blueprint.container.ExecutorServiceWrapper.run(ExecutorServiceWrapper.java:106)[15:org.apache.aries.blueprint.core:1.6.1]
                                                            at org.apache.aries.blueprint.utils.threading.impl.DiscardableRunnable.run(DiscardableRunnable.java:48)[15:org.apache.aries.blueprint.core:1.6.1]
                                                                at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_102]
                                                                    at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_102]
                                                                        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)[:1.8.0_102]
                                                                            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)[:1.8.0_102]
                                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_102]
                                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_102]
                                                                                        at java.lang.Thread.run(Thread.java:745)[:1.8.0_102]

Change-Id: I94825cd3e8ec6a33cc17a4ac76e26663ba1afe22
Signed-off-by: Sam Hague <shague@redhat.com>