Update patch set 7
Patch Set 7:

New exception, could it be related?

2017-10-25 06:26:54,833 | INFO  | nPool-1-worker-3 | ElanInstanceListener             | 341 - org.opendaylight.netvirt.elanmanager-impl - 0.4.3.SNAPSHOT | Elan instance ElanInstance{getElanInstanceName=c018532e-bf9a-4955-97da-5d574f482e43, getElanSegments=[], getElanTag=5015, getMacTimeout=300, getSegmentType=class org.opendaylight.yang.gen.v1.urn.opendaylight.netvirt.elan.rev150602.SegmentTypeVxlan, getSegmentationId=46, isExternal=false, augmentations={}} deleted from Configuration tree 
2017-10-25 06:26:54,833 | ERROR | nPool-1-worker-2 | DataStoreJobCoordinator          | 292 - org.opendaylight.genius.mdsalutil-api - 0.2.3.SNAPSHOT | Thread terminated due to uncaught exception: ForkJoinPool-1-worker-2
java.lang.NullPointerException: at index 0
	at com.google.common.collect.ObjectArrays.checkElementNotNull(ObjectArrays.java:240)[38:com.google.guava:18.0.0]
	at com.google.common.collect.ObjectArrays.checkElementsNotNull(ObjectArrays.java:231)[38:com.google.guava:18.0.0]
	at com.google.common.collect.ObjectArrays.checkElementsNotNull(ObjectArrays.java:226)[38:com.google.guava:18.0.0]
	at com.google.common.collect.ImmutableList.construct(ImmutableList.java:303)[38:com.google.guava:18.0.0]
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:258)[38:com.google.guava:18.0.0]
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:226)[38:com.google.guava:18.0.0]
	at com.google.common.util.concurrent.Futures.allAsList(Futures.java:1027)[38:com.google.guava:18.0.0]
	at org.opendaylight.genius.datastoreutils.DataStoreJobCoordinator$MainTask.run(DataStoreJobCoordinator.java:297)[292:org.opendaylight.genius.mdsalutil-api:0.2.3.SNAPSHOT]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)[:1.8.0_144]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)[:1.8.0_144]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)[:1.8.0_144]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)[:1.8.0_144]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)[:1.8.0_144]
2017-10-25 06:26:54,835 | ERROR | nPool-1-worker-0 | DataStoreJobCoordinator          | 29

Patch-set: 7
Label: Verified=0