Update patch set 1
Patch Set 1: Code-Review+1

LGTM! More FYI, and as discussed on IRC, the new CS custom check (any, not just this particular one) will not be found/loaded/work out-of-the-box in Eclipse, because of below; but that's perhaps more just an inconvenenice, not a problem which should block this from going forward.

com.puppycrawl.tools.checkstyle.api.CheckstyleException: cannot initialize module TreeWalker - Unable to instantiate 'org.opendaylight.netvirt.checkstyle.ForbiddenMethodCheck' class, it is also not possible to instantiate it as null. Please recheck that class name is specified as canonical name or read how to configure short name usage http://checkstyle.sourceforge.net/config.html#Packages. Please also recheck that provided ClassLoader to Checker is configured correctly.

Patch-set: 1
Reviewer: Gerrit User 5867 <5867@7fc14799-209e-464c-9743-7a06c2c21a81>
Label: Code-Review=+1