Fix UnsupportedOperationException in L3vpnPopulator
This was introduced by https://git.opendaylight.org/gerrit/#/c/65619/ :

2017-11-21 16:50:18,057 | ERROR | nPool-1-worker-1 | L3vpnPopulator                   | 349 - org.opendaylight.netvirt.vpnmanager-impl - 0.6.0.SNAPSHOT | Future (eventually) failed: addToLabelMapper
java.lang.UnsupportedOperationException: submit() cannot be used inside a Managed[New]TransactionRunner
	at org.opendaylight.genius.infra.NonSubmitCancelableWriteTransaction.submit(NonSubmitCancelableWriteTransaction.java:47)
	at org.opendaylight.netvirt.vpnmanager.populator.impl.L3vpnPopulator.lambda$addToLabelMapper$0(L3vpnPopulator.java:177)

Remove the call to submit.

Change-Id: I7359867b1c6135e0342a1070296976da24e0b035
Signed-off-by: Tom Pantelis <tompantelis@gmail.com>