Update patch set 7
Patch Set 7:

> new exception: 2018-02-12T00:42:29,330 | ERROR | pool-183-thread-1
 > | VpnInterfaceManager              | 367 - org.opendaylight.netvirt.vpnmanager-impl
 > - 0.6.0.SNAPSHOT | VpnInterfaceUpdateTimerTask failed
 > com.google.common.util.concurrent.UncheckedExecutionException:
 > java.lang.IllegalArgumentException: All keys must be specified for
 > class org.opendaylight.yang.gen.v1.urn.opendaylight.netvirt.l3vpn.rev130911.vpn.instance.op.data.VpnInstanceOpDataEntryKey.
 > Missing key is getVrfId. Supplied key is VpnInstanceOpDataEntryKey
 

Looks like the route designator string was null so the VpnInstanceOpDataEntryKey had a null value. Just need to check for null.

Patch-set: 7
Reviewer: Gerrit User 1842 <1842@7fc14799-209e-464c-9743-7a06c2c21a81>
Label: Verified=0