Update patch set 1
Patch Set 1: Code-Review-2

new exception: 

https://logs.opendaylight.org/releng/jenkins092/netvirt-csit-1node-openstack-ocata-gate-stateful-nitrogen/151/odl1_exception.log.gz

2017-09-01 12:24:41,208 | INFO  | nsole user karaf | core                             | 112 - org.apache.karaf.log.core - 4.0.9 | ROBOT MESSAGE: Starting test tempest.scenario.test_security_groups_basic_ops.TestSecurityGroupsBasicOps
2017-09-01 12:27:25,988 | ERROR | nPool-1-worker-0 | DataStoreJobCoordinator          | 238 - org.opendaylight.genius.mdsalutil-api - 0.3.0.SNAPSHOT | Exception when executing jobEntry: JobEntry{key='FIB-100008-128060793745465-10.10.10.9/32', mainWorker=org.opendaylight.netvirt.fibmanager.VrfEntryListener$$Lambda$756/144768941@32dd48cd, rollbackWorker=null, retryCount=0, futures=null}
java.lang.IllegalArgumentException: All keys must be specified for class org.opendaylight.yang.gen.v1.urn.opendaylight.netvirt.neutronvpn.rev150602.subnetmaps.SubnetmapKey. Missing key is getId. Supplied key is SubnetmapKey []
2017-09-01 12:29:27,761 | ERROR | nPool-1-worker-1 | DataStoreJobCoordinator          | 238 - org.opendaylight.genius.mdsalutil-api - 0.3.0.SNAPSHOT | Exception when executing jobEntry: JobEntry{key='FIB-100008-128060793745465-10.10.10.9/32', mainWorker=org.opendaylight.netvirt.fibmanager.VrfEntryListener$$Lambda$756/144768941@f90a18e, rollbackWorker=null, retryCount=0, futures=null}
java.lang.IllegalArgumentException: All keys must be specified for class org.opendaylight.yang.gen.v1.urn.opendaylight.netvirt.neutronvpn.rev150602.subnetmaps.SubnetmapKey. Missing key is getId. Supplied key is SubnetmapKey []

Patch-set: 1