Fix Java 8 javadoc compatibility in ovsdb project to make sure we pass compliation
The build was failing due to these errors:
[ERROR] ovsdb/openstack/net-virt/src/main/java/org/opendaylight/ovsdb/openstack/netvirt/api/GatewayMacResolver.java:34: error: @param name not found
 --> periodicRefresh instead of periodicReferesh
[ERROR] /Users/rashmi/UnitTests/ovsdb/openstack/net-virt/src/main/java/org/opendaylight/ovsdb/openstack/netvirt/api/GatewayMacResolver.java:27: error: bad HTML entity
--> and instead of &
[ERROR] ovsdb/openstack/net-virt-providers/src/main/java/org/opendaylight/ovsdb/openstack/netvirt/providers/openflow13/services/arp/GatewayMacResolverService.java:187: error: unknown tag: MacAddress
--> Removed Future<MacAddress> from @return
[ERROR] ovsdb/library/src/main/java/org/opendaylight/ovsdb/lib/OvsdbClient.java:74: error: @param name not found
--> monitorHandle instead of monitorHandler

Java version "1.8.0_40"

Change-Id: Ida0babd4e33b0906c5ce96234d07fef660fa8c4c
Signed-off-by: rpujar <rpujar@inocybe.com>