Update patch set 5
Patch Set 5: Code-Review-1

we found one more exception newly propping up:

2017-02-28 09:56:57,277 | WARN  | lt-dispatcher-19 | ShardDataTree                    | 220 - org.opendaylight.controller.sal-distributed-datastore - 1.5.0.SNAPSHOT | member-1-shard-default-config: Store Tx member-1-datastore-config-fe-0-txn-13199-0: Data validation failed for path /(urn:ericsson:params:xml:ns:yang:ebgp?revision=2015-09-01)bgp/networks.
org.opendaylight.yangtools.yang.data.api.schema.tree.ModifiedNodeDoesNotExistException: Node /(urn:ericsson:params:xml:ns:yang:ebgp?revision=2015-09-01)bgp/networks does not exist. Cannot apply modification to its children.
        at 

Vivek

Patch-set: 5
Label: Code-Review=-1