Update patch set 2
Patch Set 2: Code-Review-1

The last gate had the exceptions below. I have not seen these in a while. Is this because the last patch allows the possible dpid=0 though so we get openflow:0?

2017-09-27 10:43:24,938 | INFO  | nsole user karaf | core                             | 112 - org.apache.karaf.log.core - 4.0.9 | ROBOT MESSAGE: Starting test Delete Networks
org.opendaylight.yangtools.yang.data.api.schema.tree.ModifiedNodeDoesNotExistException: Node /(urn:opendaylight:inventory?revision=2013-08-19)nodes/node/node[{(urn:opendaylight:inventory?revision=2013-08-19)id=openflow:0}] does not exist. Cannot apply modification to its children.
TransactionCommitFailedException{message=Data did not pass validation., errorList=[RpcError [message=Data did not pass validation., severity=ERROR, errorType=APPLICATION, tag=operation-failed, applicationTag=null, info=null, cause=org.opendaylight.yangtools.yang.data.api.schema.tree.ModifiedNodeDoesNotExistException: Node /(urn:opendaylight:inventory?revision=2013-08-19)nodes/node/node[{(urn:opendaylight:inventory?revision=2013-08-19)id=openflow:0}] does not exist. Cannot apply modification to its children.]]}

Patch-set: 2
Label: Code-Review=-1