Update patch set 4
Patch Set 4: Code-Review-1

looks like a new exception that repeats many times:

org.opendaylight.yangtools.yang.data.api.schema.tree.ModifiedNodeDoesNotExistException: Node /(urn:huawei:params:xml:ns:yang:l3vpn?revision=2014-08-15)vpn-interfaces/vpn-interface/vpn-interface[{(urn:huawei:params:xml:ns:yang:l3vpn?revision=2014-08-15)name=18421606094981:br-physnet1-pa:trunk}]/AugmentationIdentifier{childNames=[(urn:opendaylight:netvirt:l3vpn?revision=2013-09-11)adjacency]} does not exist. Cannot apply modification to its children.

Patch-set: 4
Label: Code-Review=-1