Update patch set 1
Patch Set 1:

> (1 comment)
In oxygen branch I was getting below compilation error as below that is why final was added:

VpnInterfaceManager.java:1522: Distance between variable 'futures' declaration and its first usage is 4, but allowed 3.  Consider making that variable  final if you still need to store its value in advance (before method calls that might have side effects on the original value). [VariableDeclarationUsageDistance]

You can refer the build failure logs in below oxygen build.
https://git.opendaylight.org/gerrit/#/c/73920/


This was not observed in case of master branch and the build went fine.

Patch-set: 1
Label: Verified=0