Update patch set 6
Patch Set 6: Code-Review-1

new exception: 2018-02-12T00:42:29,330 | ERROR | pool-183-thread-1 | VpnInterfaceManager              | 367 - org.opendaylight.netvirt.vpnmanager-impl - 0.6.0.SNAPSHOT | VpnInterfaceUpdateTimerTask failed
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException: All keys must be specified for class org.opendaylight.yang.gen.v1.urn.opendaylight.netvirt.l3vpn.rev130911.vpn.instance.op.data.VpnInstanceOpDataEntryKey. Missing key is getVrfId. Supplied key is VpnInstanceOpDataEntryKey []

Patch-set: 6
Label: Code-Review=-1