Update patch set 3
Patch Set 3:

Kiran, can you take another look at this? Looks like the exception is still in the logs.

https://logs.opendaylight.org/releng/jenkins092/netvirt-csit-1node-openstack-ocata-gate-stateful-nitrogen/145/odl1_exception.log.gz

2017-08-30 17:25:12,296 | INFO  | nsole user karaf | core                             | 112 - org.apache.karaf.log.core - 4.0.9 | ROBOT MESSAGE: Starting test Verify Datapath After OVS Restart
java.lang.IllegalArgumentException: Node (urn:opendaylight:netvirt:fibmanager?revision=2015-03-30)vrfEntry[{(urn:opendaylight:netvirt:fibmanager?revision=2015-03-30)destPrefix=10.10.10.250/32}] is missing mandatory descendant /(urn:opendaylight:netvirt:fibmanager?revision=2015-03-30)origin
java.lang.IllegalArgumentException: Node (urn:opendaylight:netvirt:fibmanager?revision=2015-03-30)vrfEntry[{(urn:opendaylight:netvirt:fibmanager?revision=2015-03-30)destPrefix=10.10.10.250/32}] is missing mandatory descendant /(urn:opendaylight:netvirt:fibmanager?revision=2015-03-30)origin
java.lang.IllegalArgumentException: Node (urn:opendaylight:netvirt:fibmanager?revision=2015-03-30)vrfEntry[{(urn:opendaylight:netvirt:fibmanager?revision=2015-03-30)destPrefix=10.10.10.250/32}] is missing mandatory descendant /(urn:opendaylight:netvirt:fibmanager?revision=2015-03-30)origin
java.lang.IllegalArgumentException: Node (urn:opendaylight:netvirt:fibmanager?revision=2015-03-30)vrfEntry[{(urn:opendaylight:netvirt:fibmanager?revision=2015-03-30)destPrefix=10.10.10.250/32}] is missing mandatory descendant /(urn:opendaylight:netvirt:fibmanager?revision=2015-03-30)origin
2017-08-30 17:25:15,441 | ERROR | nPool-1-worker-0 | DataStoreJobCoordinator          | 238 - org.opendaylight.genius.mdsalutil-api - 0.3.0.SNAPSHOT | Exception when executing jobEntry: JobEntry{key='VPNINTERFACE-277645428756599:br-physnet1-pa:trunk', mainWorker=org.opendaylight.netvirt.vpnmanager.TunnelInterfaceStateListener$UpdateVpnInterfaceOnTunnelEvent@22838dcf, rollbackWorker=null, retryCount=0, futures=null}
java.lang.RuntimeException: TransactionCommitFailedException{message=canCommit encountered an unexpected failure, errorList=[RpcError [message=canCommit encountered an unexpected failure, severity=ERROR, errorType=APPLICATION, tag=operation-failed, applicationTag=null, info=null, cause=java.lang.IllegalArgumentException: Node (urn:opendaylight:netvirt:fibmanager?revision=2015-03-30)vrfEntry[{(urn:opendaylight:netvirt:fibmanager?revision=2015-03-30)destPrefix=10.10.10.250/32}] is missing mandatory descendant /(urn:opendaylight:netvirt:fibmanager?revision=2015-03-30)origin]]}
Caused by: TransactionCommitFailedException{message=canCommit encountered an unexpected failure, errorList=[RpcError [message=canCommit encountered an unexpected failure, severity=ERROR, errorType=APPLICATION, tag=operation-failed, applicationTag=null, info=null, cause=java.lang.IllegalArgumentException: Node (urn:opendaylight:netvirt:fibmanager?revision=2015-03-30)vrfEntry[{(urn:opendaylight:netvirt:fibmanager?revision=2015-03-30)destPrefix=10.10.10.250/32}] is missing mandatory descendant /(urn:opendaylight:netvirt:fibmanager?revision=2015-03-30)origin]]}
	at org.opendaylight.controller.md.sal.dom.broker.impl.TransactionCommitFailedExceptionMapper.newWithCause(TransactionCommitFailedExceptionMapper.java:37)[202:org.opendaylight.controller.sal-broker-impl:1.6.0.SNAPSHOT]
	at org.opendaylight.controller.md.sal.dom.broker.impl.TransactionCommitFailedExceptionMapper.newWithCause(TransactionCommitFailedExceptionMapper.java:18)[202:org.opendaylight.controller.sal-broker-impl:1.6.0.SNAPSHOT]
	at org.opendaylight.yangtools.util.concurrent.ExceptionMapper.apply(ExceptionMapper.java:103)[367:org.opendaylight.yangtools.util:1.2.0.SNAPSHOT]
	at org.opendaylight.controller.cluster.databroker.ConcurrentDOMDataBroker.handleException(ConcurrentDOMDataBroker.java:231)[212:org.opendaylight.controller.sal-distributed-datastore:1.6.0.SNAPSHOT]
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:686)[27:com.google.guava:22.0.0]
	at com.google.common.util.concurrent.SettableFuture.setException(SettableFuture.java:54)[27:com.google.guava:22.0.0]
Caused by: java.lang.IllegalArgumentException: Node (urn:opendaylight:netvirt:fibmanager?revision=2015-03-30)vrfEntry[{(urn:opendaylight:netvirt:fibmanager?revision=2015-03-30)destPrefix=10.10.10.250/32}] is missing mandatory descendant /(urn:opendaylight:netvirt:fibmanager?revision=2015-03-30)origin

Patch-set: 3