Update patch set 4
Patch Set 4:

Hi Kiran,

We still have the below ActivateMIP exception:

And also, we need to put ERROR instead of INFO for:
 INFO  | pool-49-thread-1 | BgpRouter                        | 364 - org.opendaylight.netvirt.bgpmanager-impl - 0.4.0.SNAPSHOT | Failed connecting to BGP confi


2017-02-27 19:31:34,385 | ERROR | lt-dispatcher-21 | BgpConfigurationManager          | 364 - org.opendaylight.netvirt.bgpmanager-impl - 0.4.0.SNAPSHOT | IO Exception got while activating mip:  
java.io.IOException: Cannot run program "cluster": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)[:1.8.0_121]
	at java.lang.Runtime.exec(Runtime.java:620)[:1.8.0_121]
	at java.lang.Runtime.exec(Runtime.java:450)[:1.8.0_121]
	at java.lang.Runtime.exec(Runtime.java:347)[:1.8.0_121]
	at org.opendaylight.netvirt.bgpmanager.BgpConfigurationManager.activateMIP(BgpConfigurationManager.java:1187)[364:org.opendaylight.netvirt.bgpmanager-impl:0.4.0.SNAPSHOT]
	at org.opendaylight.netvirt.bgpmanager.BgpConfigurationManager.lambda$setEntityOwnershipService$1(BgpConfigurationManager.java:330)[364:org.opendaylight.netvirt.bgpmanager-impl:0.4.0.SNAPSHOT]
	at 

Vivek

Patch-set: 4
Label: Verified=0