Update patch set 8
Patch Set 8:

Kiran, Vivek, can you look at the csit results? looks like a new exception: 

2017-09-18 09:30:48,944 | ERROR | nPool-2-worker-2 | DataStoreJobCoordinator          | 243 - org.opendaylight.genius.mdsalutil-api - 0.4.0.SNAPSHOT | Exception when executing jobEntry: JobEntry{key='VPNINTERFACE-null', mainWorker=org.opendaylight.netvirt.fibmanager.VrfEntryListener$CleanupVpnInterfaceWorker@31c469, rollbackWorker=null, retryCount=0, futures=null}
java.lang.IllegalArgumentException: All keys must be specified for class org.opendaylight.yang.gen.v1.urn.huawei.params.xml.ns.yang.l3vpn.rev140815.vpn.interfaces.VpnInterfaceKey. Missing key is getName. Supplied key is VpnInterfaceKey []
2017-09-18 09:30:50,790 | ERROR | nPool-2-worker-1 | DataStoreJobCoordinator          | 243 - org.opendaylight.genius.mdsalutil-api - 0.4.0.SNAPSHOT | Exception when executing jobEntry: JobEntry{key='VPNINTERFACE-null', mainWorker=org.opendaylight.netvirt.fibmanager.VrfEntryListener$CleanupVpnInterfaceWorker@5114b9d3, rollbackWorker=null, retryCount=0, futures=null}
java.lang.IllegalArgumentException: All keys must be specified for class org.opendaylight.yang.gen.v1.urn.huawei.params.xml.ns.yang.l3vpn.rev140815.vpn.interfaces.VpnInterfaceKey. Missing key is getName. Supplied key is VpnInterfaceKey []

Patch-set: 8
Reviewer: Gerrit User 773 <773@7fc14799-209e-464c-9743-7a06c2c21a81>
Label: Verified=0